version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SELENIUM_URL=http://selenium:4444/wd/hub
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome
    shm_size: 2g
    ports:
      - "4444:4444"
