version: '3'
services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    environment:
      - SELENIUM_URL=http://selenium:4444/wd/hub
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900" # Optional: for viewing VNC if needed
