version: '3'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SELENIUM_URL=http://selenium:4444/wd/hub
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
